export const PathLink = {
  login: '/login',
  pickListQty: '/pick-list',
  pickListQtyDetail: '/pick-list/:doNo',
  pickListQtyDetailPick: '/pick-list/:doNo/:id',
  flowmeterReading: "/flowmeter-reading",
  flowmeterReadingDetail: "/flowmeter-reading/:id",
  onSiteVerification: "/on-site-verification",
  onSiteVerificationDetail: "/on-site-verification/:id",
  onSiteVerificationDetailSerial: "/on-site-verification/:id/:doNo",
  custSiteVerification: "/cust-site-verification",
  custSiteVerificationAccountCode: "/cust-site-verification/:id",
  custSiteVerificationDetail: "/cust-site-verification/:id/:accountCode",
  custSiteVerificationDetailSerial: "/cust-site-verification/:id/:accountCode/:doNo",
  userAccess: "/user-access",
  driverEcr: "/driver-ecr",
  driverEcrDetail: "/driver-ecr/:id",
  ecr: "/ecr",
  ecrDetail: "/ecr/:id",
}