const prefix = import.meta.env.VITE_ENVIRONMENT + "/";

export const LocalStorage = {
  PUBLIC_KEY: prefix + "LMS/MASTER_PUBLIC_KEY",
  ACCESS_TOKEN: prefix + "LMS/ACCESS_TOKEN",
  MODULE_GRANT: prefix + "LMS/MODULE_GRANT",
  FIRST_TIME_LOGIN: prefix + "LMS/FIRST_TIME_LOGIN",
  COMPANY_ID: prefix + "LMS/COMPANY_ID",
};

export const SessionStorage = {
  MODULE_API: prefix + "LMS/MODULE_API",
  MODULE_VIEWER_API: prefix + "LMS/MODULE_VIEWER_API",
  MODULE_PUBLIC_KEY: prefix + "LMS/MODULE_PUBLIC_KEY",
  BRANCH_CODE: prefix + "LMS/BRANCH_CODE",
  DIVISION_BRANCH_NAME: prefix + "LMS/DIVISION_BRANCH_NAME",
  DEFAULT_CURRENCY_CODE: prefix + "LMS/DEFAULT_CURRENCY_CODE",
  USER_DIMENSION: prefix + "LMS/USER_DIMENSION",
  DIMENSION_CONFIG: prefix + "LMS/DIMENSION_CONFIG",
  DIMENSION_SHORT_NAMES: prefix + "LMS/DIMENSION_SHORT_NAMES",
};

