export default {
    pReceiptactive: require('./p_receipt_active.png'),
    pReceipt: require('./p_receipt.png'),
    processing: require('./processing.png'),
    processingactive: require('./processing_active.png'),
    qcapprove:require('./qc_approval.png'),
    qcapproveactive:require('./qc_approval_active.png'),
    posted:require('./posted.png'),
    postedactive:require('./posted_active.png'),
    unposted:require('./unposted.png'),
    unpostedactive:require('./unposted_active.png'),
    request:require('./request.png'),
    requestactive:require('./request_active.png'),
    approval:require('./approval.png'),
    approvalactive:require('./approval_active.png'),
    picklist:require('./picklist.png'),
    picklistactive:require('./picklist_active.png'),
    leedennox:require('./leedennox.png'),
    calculator:require('./calculator.png'),
    calculatoractive:require('./calculator_active.png'),
    weldingprice:require('./weldingprice.png'),
    weldingpriceactive:require('./weldingprice_active.png'),
    safetyprice:require('./safetyprice.png'),
    safetypriceactive:require('./safetyprice_active.png'),
    fireprice:require('./fireprice.png'),
    firepriceactive:require('./fireprice_active.png'),
    gascatalogue:require('./gascatalogue.png'),
    gascatalogueactive:require('./gascatalogue_active.png'),
    weldingcatalogue:require('./weldingcatalogue.png'),
    weldingcatalogueactive:require('./weldingcatalogue_active.png'),
    corpcatalogue:require('./corpcatalogue.png'),
    corpcatalogueactive:require('./corpcatalogue_active.png'),
    safetycatalogue:require('./safetycatalogue.png'),
    safetycatalogueactive:require('./safetycatalogue_active.png'),
    firecatalogue:require('./firecatalogue.png'),
    firecatalogueactive:require('./firecatalogue_active.png'),
    gasprice:require('./gasprice.png'),
    gaspriceactive:require('./gasprice_active.png'),
    cylinder:require('./cylinder.png'),
    cylinderactive:require('./cylinder_active.png'),
    new: require('./new.png'),
    scheduled:require('./scheduled.png'),
    scheduledactive:require('./scheduled_active.png'),
    transport:require('./transport.png'),
    transportactive:require('./transport_active.png'),
    
};